language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
env:
  - XML=rexml
  - XML=nokogiri
matrix:
  allow_failures:
    - rvm: jruby-18mode
      env: XML=nokogiri
    - rvm: jruby-19mode
      env: XML=nokogiri
notifications:
  email:
    recipients:
      - dev@recurly.com
