language: ruby
script:
  - bundle exec rake spec
  - gem build recurly.gemspec
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - jruby
  - rbx
env:
  - XML=rexml
  - XML=nokogiri
matrix:
  allow_failures:
    - rvm: jruby-19mode
      env: XML=nokogiri
