language: ruby
script:
  - bundle exec rake spec
  - gem build recurly.gemspec
cache: bundler
sudo: false
before_install:
  - gem update --system
  - gem update bundler
rvm:
  - jruby-9.1.9.0
  - jruby-9000
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
env:
  - XML=rexml
  - XML=nokogiri
matrix:
  allow_failures:
    - rvm: 1.9.3-p551
    - rvm: 2.0.0-p648
    - rvm: 2.1.10
    - rvm: jruby-9.1.9.0
